language: python
python:
  - 3.5
  - 3.6
install:
  - pip install pipenv --upgrade
  - pipenv install --dev
script:
  - pipenv run pytest
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true